# Generated by Django 4.2.30 on 2026-09-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_meal_created_by_waterintake_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='waterintake',
            options={'ordering': ['-date']},
        ),
    ]
