# Generated by Django 4.2.30 on 2026-09-09 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_meal_options_alter_waterintake_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='waterintake',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
