# Generated by Django 4.2.30 on 2026-09-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_exercise_description_exercise_rest_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En progreso'), ('finished', 'Finalizado')], default='finished', max_length=20),
        ),
    ]
