# Generated by Django 4.2.30 on 2026-09-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexercise',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
