# Generated by Django 4.2.30 on 2026-09-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_routineexercise_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='generated_by_ai',
        ),
        migrations.AddField(
            model_name='routine',
            name='source',
            field=models.CharField(choices=[('ai', 'IA'), ('self', 'Creado por vos'), ('trainer', 'Asignado por entrenador')], default='self', max_length=20),
        ),
    ]
