# Generated by Django 4.2.30 on 2026-09-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('trainer', 'Trainer'), ('gym_admin', 'Gym Admin'), ('gym_owner', 'Gym Owner'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
