# Generated by Django 4.2.30 on 2026-09-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rank',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.CharField(blank=True, choices=[('mortal', 'Mortal'), ('hero_in_training', 'Héroe en entrenamiento'), ('argonaut', 'Argonauta'), ('demigod', 'Semidiós'), ('titan', 'Titán'), ('olympian_god', 'Dios del Olimpo')], max_length=20),
        ),
    ]
