# Generated by Django 4.2.30 on 2026-09-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gymplan_gym_qr_code_gymmembership_assigned_trainer_and_more'),
        ('accounts', '0005_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_by', to='gyms.gym'),
        ),
    ]
